services:
  # Your Website
  web:
    build: .
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "80:5000"
    networks:
      - my-net

  # The GitHub Runner
  runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    restart: always
    environment:
      - REPO_URL=${GITHUB_REPO_URL}
      - ACCESS_TOKEN=${GITHUB_TOKEN}
      - RUNNER_NAME=docker-pi-runner
      - RUNNER_WORKDIR=/tmp/runner
      - DISABLE_AUTO_UPDATE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-net

networks:
  my-net:
    driver: bridge

logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
