name: Deploy-to-Raspberry-Pi

# Trigger on push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Check out the latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Rebuild and Restart Docker
      - name: Deploy with Docker Compose
        run: |
          docker compose up -d --build web
          
          # Optional: Remove old, unused images to save SD card space
          docker image prune -f
